@HOST = http://localhost:4000/api

###

GET  {{HOST}}/auth/hash
     ?data=1
     &check=

###

POST {{HOST}}/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "name": "test"
}

###

POST {{HOST}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

DELETE  {{HOST}}/auth/logout
Authorization: Bearer test

###

POST {{HOST}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test updated"
}

###

GET {{HOST}}/auth/user
Authorization: Bearer test

###

POST {{HOST}}/auth/upload
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="kucing-rumahan-unsplash-768x512.jpeg"
Content-Type: image/jpeg

< C:/Users/fys/Downloads/kucing-rumahan-unsplash-768x512.jpeg
--Boundary--

###
# without value
POST {{HOST}}/auth/upload
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename=""
Content-Type: application/octet-stream

<
--Boundary--

###